# Generated by Django 3.0.7 on 2020-07-07 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='제목')),
                ('body', models.TextField(verbose_name='내용')),
                ('nickname', models.CharField(max_length=10, verbose_name='닉네임')),
                ('created_at', models.DateTimeField(auto_now=True, verbose_name='작성시간')),
            ],
        ),
    ]
