# Generated by Django 3.0.7 on 2020-08-08 01:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_recomment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='body',
            field=models.CharField(max_length=100, verbose_name='re'),
        ),
        migrations.AlterField(
            model_name='recomment',
            name='body',
            field=models.CharField(max_length=100, verbose_name='re-reply'),
        ),
    ]
